import { Utils } from './player/utils'
import type { DiscordTrack } from './types'
function make_media(data: {title: string; media_uri: string; duration: number;}): DiscordTrack{
    return Utils.track_to_discord_track({
        uid: data.title,
        title: data.title,
        artists: [{name: "Sudo", uri: null}],
        duration: data.duration ?? 0,
        media_uri: data.media_uri,
        imported_id: "discord-imported-media"
    });
}

export const MEDIA = [
	make_media({"title":"5-seconds-of-silence.mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\5-seconds-of-silence.mp3","duration":5}),
	make_media({"title":"A Wendy’s Christmas.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\A Wendy’s Christmas.m4a","duration":135}),
	make_media({"title":"Anything.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Anything.m4a","duration":130}),
	make_media({"title":"ArianaGrandAYE.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\ArianaGrandAYE.m4a","duration":120}),
	make_media({"title":"BabyTronxNinoPaidWhatstheWordProdPierre.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\BabyTronxNinoPaidWhatstheWordProdPierre.m4a","duration":116}),
	make_media({"title":"Big Nose.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Big Nose.m4a","duration":155}),
	make_media({"title":"Blair Witch.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Blair Witch.m4a","duration":158}),
	make_media({"title":"BoutMyMoneyMaster.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\BoutMyMoneyMaster.m4a","duration":116}),
	make_media({"title":"BrokenLordsavemycompluter.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\BrokenLordsavemycompluter.m4a","duration":122}),
	make_media({"title":"BrolyTiming(otherset).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\BrolyTiming(otherset).m4a","duration":92}),
	make_media({"title":"Broly_Timing(feat. Kanesta).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Broly_Timing(feat. Kanesta).m4a","duration":160}),
	make_media({"title":"CherryBlossom(LD).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\CherryBlossom(LD).m4a","duration":134}),
	make_media({"title":"Clappin.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Clappin.m4a","duration":162}),
	make_media({"title":"decaysmile.mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\decaysmile.mp3","duration":84}),
	make_media({"title":"Facemask Cologne.mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Facemask Cologne.mp3","duration":122}),
	make_media({"title":"Freddy Kreuger.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Freddy Kreuger.m4a","duration":125}),
	make_media({"title":"Freddy Spazbear.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Freddy Spazbear.m4a","duration":126}),
	make_media({"title":"FreddyKreuger(luhrevision).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\FreddyKreuger(luhrevision).m4a","duration":125}),
	make_media({"title":"FreeCrankyKong.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\FreeCrankyKong.m4a","duration":104}),
	make_media({"title":"FrightNight.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\FrightNight.m4a","duration":133}),
	make_media({"title":"Froze Interlude.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Froze Interlude.m4a","duration":45}),
	make_media({"title":"Fuck SSSniperwolf (Zayboy final verse).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Fuck SSSniperwolf (Zayboy final verse).m4a","duration":210}),
	make_media({"title":"fucksniperwolf(fnl).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\fucksniperwolf(fnl).m4a","duration":210}),
	make_media({"title":"Gmail Perc.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Gmail Perc.m4a","duration":91}),
	make_media({"title":"Gogeta 2.mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Gogeta 2.mp3","duration":115}),
	make_media({"title":"Indie White Girls.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Indie White Girls.m4a","duration":129}),
	make_media({"title":"IRLMoneyGlitch(Good_).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\IRLMoneyGlitch(Good_).m4a","duration":105}),
	make_media({"title":"IRLMoneyGlitch.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\IRLMoneyGlitch.m4a","duration":168}),
	make_media({"title":"IStaySilly.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\IStaySilly.m4a","duration":170}),
	make_media({"title":"It’s A Popeyes Christmas.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\It’s A Popeyes Christmas.m4a","duration":135}),
	make_media({"title":"Jigsaw.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Jigsaw.m4a","duration":164}),
	make_media({"title":"Krampus (Mastered 2).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Krampus (Mastered 2).m4a","duration":137}),
	make_media({"title":"LafouandMorty.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\LafouandMorty.m4a","duration":120}),
	make_media({"title":"Lookatyou.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Lookatyou.m4a","duration":107}),
	make_media({"title":"Mewmore  Join Avenue (Pokémon Black 2 & White 2).mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Mewmore  Join Avenue (Pokémon Black 2 & White 2).mp3","duration":300}),
	make_media({"title":"Miscellaneous Christmas rap.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Miscellaneous Christmas rap.m4a","duration":105}),
	make_media({"title":"moose-final.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\moose-final.m4a","duration":126}),
	make_media({"title":"Moving On.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Moving On.m4a","duration":100}),
	make_media({"title":"Naught List (mastered).m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Naught List (mastered).m4a","duration":105}),
	make_media({"title":"New Specimen.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\New Specimen.m4a","duration":168}),
	make_media({"title":"No more.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\No more.m4a","duration":99}),
	make_media({"title":"Not your type Groovepill x lelo unfinished.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Not your type Groovepill x lelo unfinished.m4a","duration":167}),
	make_media({"title":"No_Liver.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\No_Liver.m4a","duration":122}),
	make_media({"title":"no_sleep - final.wav","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\no_sleep - final.wav","duration":109}),
	make_media({"title":"OneMoreDayniggaleaveyourshittyrelationshipnotminethoIlovemygirl.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\OneMoreDayniggaleaveyourshittyrelationshipnotminethoIlovemygirl.m4a","duration":208}),
	make_media({"title":"petethecat.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\petethecat.m4a","duration":145}),
	make_media({"title":"PinkEye.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\PinkEye.m4a","duration":144}),
	make_media({"title":"Plan B.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Plan B.m4a","duration":136}),
	make_media({"title":"Pointoinkling Chip.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Pointoinkling Chip.m4a","duration":95}),
	make_media({"title":"Ronald Reagan Crack.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Ronald Reagan Crack.m4a","duration":64}),
	make_media({"title":"Salsa 2.mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Salsa 2.mp3","duration":156}),
	make_media({"title":"Sanity.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Sanity.m4a","duration":182}),
	make_media({"title":"Scarface v2 2.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Scarface v2 2.m4a","duration":238}),
	make_media({"title":"Shiny.wav","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Shiny.wav","duration":109}),
	make_media({"title":"Silly Poppa.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Silly Poppa.m4a","duration":120}),
	make_media({"title":"SkunkyGun.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\SkunkyGun.m4a","duration":156}),
	make_media({"title":"skunky_gun - final.wav","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\skunky_gun - final.wav","duration":156}),
	make_media({"title":"Sleep Deprived.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Sleep Deprived.m4a","duration":113}),
	make_media({"title":"Squiliam.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Squiliam.m4a","duration":135}),
	make_media({"title":"triple threat done pt1.mp3","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\triple threat done pt1.mp3","duration":189}),
	make_media({"title":"tron fuck turkey man_1 OPEN.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\tron fuck turkey man_1 OPEN.m4a","duration":286}),
	make_media({"title":"True Story.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\True Story.m4a","duration":243}),
	make_media({"title":"Tylenol PM.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Tylenol PM.m4a","duration":97}),
	make_media({"title":"Unreal.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\Unreal.m4a","duration":157}),
	make_media({"title":"WhereyaAuntie.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\WhereyaAuntie.m4a","duration":117}),
	make_media({"title":"WORK!.m4a","media_uri":"C:\\dev\\Illusi\\lib-origin\\illusicord\\media\\WORK!.m4a","duration":112})
];