declare namespace NodeJS {
	export interface ProcessEnv {
		EXPO_PUBLIC_SUPABASE_PROJECT_URL: string;
		EXPO_PUBLIC_SUPABASE_PUBLIC_KEY: string;
		YOUTUBE_COOKIE_JAR: string;
		YOUTUBE_MUSIC_COOKIE_JAR: string;
		SPOTIFY_COOKIE_JAR: string;
		SOUNDCLOUD_COOKIE_JAR: string;
		AMAZON_MUSIC_COOKIE_JAR: string;
		APPLE_MUSIC_COOKIE_JAR: string;
		JNOVEL_COOKIE_JAR: string;
		INSTAGRAM_COOKIE_JAR: string;
		GOOGLE_TRANSLATE_COOKIE_JAR: string;
		BANDLAB_COOKIE_JAR: string;
	}
}
