ALTER TABLE `backpack_deleted` ADD `audiomack_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `deezer_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `pandora_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `tidal_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `acousticness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `danceability` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `energy` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `instrumentalness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `liveness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `speechiness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack_deleted` ADD `valence` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `audiomack_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `deezer_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `pandora_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `tidal_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `acousticness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `danceability` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `energy` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `instrumentalness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `liveness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `speechiness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `backpack` ADD `valence` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `audiomack_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `deezer_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `pandora_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `tidal_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `acousticness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `danceability` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `energy` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `instrumentalness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `liveness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `speechiness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recently_played_tracks` ADD `valence` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `audiomack_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `deezer_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `pandora_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `tidal_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `acousticness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `danceability` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `energy` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `instrumentalness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `liveness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `speechiness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks_deleted` ADD `valence` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `audiomack_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `deezer_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `pandora_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `tidal_id` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `acousticness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `danceability` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `energy` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `instrumentalness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `liveness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `speechiness` numeric DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `tracks` ADD `valence` numeric DEFAULT 0 NOT NULL;