export interface YTCFG {
    CLIENT_CANARY_STATE: string
    DEVICE: string
    DISABLE_YT_IMG_DELAY_LOADING: boolean
    ELEMENT_POOL_DEFAULT_CAP: number
    EVENT_ID: string
    EXPERIMENT_FLAGS: ExperimentFlags
    GAPI_HINT_PARAMS: string
    GAPI_HOST: string
    GAPI_LOCALE: string
    GL: string
    GOOGLE_FEEDBACK_PRODUCT_ID: string
    GOOGLE_FEEDBACK_PRODUCT_DATA: GoogleFeedbackProductData
    HL: string
    HTML_DIR: string
    HTML_LANG: string
    ID_TOKEN: string
    INNERTUBE_API_KEY: string
    INNERTUBE_API_VERSION: string
    INNERTUBE_CLIENT_NAME: string
    INNERTUBE_CLIENT_VERSION: string
    INNERTUBE_CONTEXT: InnertubeContext
    INNERTUBE_CONTEXT_CLIENT_NAME: number
    INNERTUBE_CONTEXT_CLIENT_VERSION: string
    INNERTUBE_CONTEXT_GL: string
    INNERTUBE_CONTEXT_HL: string
    LATEST_ECATCHER_SERVICE_TRACKING_PARAMS: LatestEcatcherServiceTrackingParams
    LOGGED_IN: boolean
    PAGE_BUILD_LABEL: string
    PAGE_CL: number
    scheduler: Scheduler
    SERVER_NAME: string
    SESSION_INDEX: string
    SIGNIN_URL: string
    VISITOR_DATA: string
    WEB_PLAYER_CONTEXT_CONFIGS: WebPlayerContextConfigs
    XSRF_FIELD_NAME: string
    XSRF_TOKEN: string
    YPC_MB_URL: string
    YTR_FAMILY_CREATION_URL: string
    SERVER_VERSION: string
    REUSE_COMPONENTS: boolean
    STAMPER_STABLE_LIST: boolean
    DATASYNC_ID: string
    SERIALIZED_CLIENT_CONFIG_DATA: string
    LOCATION_PLAYABILITY_TOKEN: string
    LIVE_CHAT_BASE_TANGO_CONFIG: LiveChatBaseTangoConfig
    FEXP_EXPERIMENTS: number[]
    LIVE_CHAT_SEND_MESSAGE_ACTION: string
    ROOT_VE_TYPE: number
    CLIENT_PROTOCOL: string
    CLIENT_TRANSPORT: string
    TIME_CREATED_MS: number
    BUTTON_REWORK: boolean
    LOGIN_INFO: string
    VALID_SESSION_TEMPDATA_DOMAINS: string[]
    WORKER_PERFORMANCE_URL: WorkerPerformanceUrl
    RAW_COLD_CONFIG_GROUP: RawColdConfigGroup
    RAW_HOT_CONFIG_GROUP: RawHotConfigGroup
    SERIALIZED_HOT_HASH_DATA: string
    SERIALIZED_COLD_HASH_DATA: string
    PERSIST_IDENTITY_IFRAME_URL: PersistIdentityIframeUrl
    WORKER_SERIALIZATION_URL: WorkerSerializationUrl
    LOG_STICKINESS: boolean
    USER_SESSION_ID: string
    VISIBILITY_TIME_BETWEEN_JOBS_MS: number
    START_IN_THEATER_MODE: boolean
    START_IN_FULL_WINDOW_MODE: boolean
    SERVICE_WORKER_PROMPT_NOTIFICATIONS: boolean
    SBOX_LABELS: SboxLabels
    ONE_PICK_URL: string
    NO_EMPTY_DATA_IMG: boolean
    MENTIONS_EDU_HELP_LINK: string
    DEFERRED_DETACH: boolean
    RECAPTCHA_V3_SITEKEY: string
    PLAYER_JS_URL: string
    PLAYER_CSS_URL: string
    LINK_GAL_DOMAIN: string
    LINK_OIS_DOMAIN: string
    IS_TABLET: boolean
    LINK_API_KEY: string
    DISABLE_WARM_LOADS: boolean
    ZWIEBACK_PING_URLS: string[]
    VOZ_API_KEY: string
    STS: number
    SBOX_SETTINGS: SboxSettings
    SBOX_JS_URL: string
}

export interface ExperimentFlags {
    H5_enable_full_pacf_logging: boolean
    H5_use_async_logging: boolean
    PremiumClientSharedConfig__enable_att_context_processor: boolean
    PremiumClientSharedConfig__enable_att_for_get_premium_on_web_client: boolean
    ab_det_apb_b: boolean
    ab_det_el_h: boolean
    action_companion_center_align_description: boolean
    allow_skip_networkless: boolean
    att_web_record_metrics: boolean
    browse_next_continuations_migration_playlist: boolean
    c3_watch_page_component: boolean
    cache_utc_offset_minutes_in_pref_cookie: boolean
    cancel_pending_navs: boolean
    check_user_lact_at_prompt_shown_time_on_web: boolean
    clean_up_manual_attribution_header: boolean
    clear_user_partitioned_ls: boolean
    client_respect_autoplay_switch_button_renderer: boolean
    cold_missing_history: boolean
    comments_simplebox_round_avatar: boolean
    compress_gel: boolean
    csi_config_handling_infra: boolean
    csi_on_gel: boolean
    decorate_autoplay_renderer: boolean
    defer_menus: boolean
    defer_overlays: boolean
    defer_rendering_outside_visible_area: boolean
    deprecate_csi_has_info: boolean
    deprecate_pair_servlet_enabled: boolean
    desktop_add_to_playlist_renderer_dialog_popup: boolean
    desktop_animate_miniplayer: boolean
    desktop_delay_player_resizing: boolean
    desktop_enable_dmpanel_click_drag_scroll: boolean
    desktop_enable_dmpanel_scroll: boolean
    desktop_enable_dmpanel_wheel_scroll: boolean
    desktop_keyboard_capture_keydown_killswitch: boolean
    desktop_mix_use_sampled_color_for_bottom_bar: boolean
    desktop_mix_use_sampled_color_for_bottom_bar_search: boolean
    desktop_mix_use_sampled_color_for_bottom_bar_watch_next: boolean
    desktop_notification_set_title_bar: boolean
    desktop_shorts_volume_controls: boolean
    desktop_sparkles_light_cta_button: boolean
    desktop_swipeable_guide: boolean
    desktop_use_new_history_manager: boolean
    disable_cached_masthead_data: boolean
    disable_child_node_auto_formatted_strings: boolean
    disable_dependency_injection: boolean
    disable_enf_isd: boolean
    disable_features_for_supex: boolean
    disable_legacy_desktop_remote_queue: boolean
    disable_log_to_visitor_layer: boolean
    disable_pacf_logging_for_memory_limited_tv: boolean
    disable_pause_on_linked_comment_nav: boolean
    disable_safari_ui_status_check: boolean
    disable_simple_mixed_direction_formatted_strings: boolean
    disable_super_chat_buy_button: boolean
    disable_visibility_resume_during_dialogs: boolean
    embeds_transport_use_scheduler: boolean
    embeds_web_nwl_disable_nocookie: boolean
    empty_attributed_string_killswitch: boolean
    enable_ab_report_on_errorscreen: boolean
    enable_ab_rp_int: boolean
    enable_active_view_display_ad_renderer_web_home: boolean
    enable_ad_context_in_vss_pings: boolean
    enable_ads_web_ep_buenos_aires_and_padding_fix: boolean
    enable_async_ab_enf: boolean
    enable_buenos_aires_typography: boolean
    enable_button_behavior_reuse: boolean
    enable_channel_page_modern_profile_section: boolean
    enable_chrome_related_websites_storage_access: boolean
    enable_client_creator_goal_ticker_bar_revamp: boolean
    enable_client_only_wiz_direct_reactions: boolean
    enable_client_only_wiz_flush_queue_fix: boolean
    enable_client_only_wiz_ordered_reaction_execution: boolean
    enable_client_sli_logging: boolean
    enable_client_streamz_web: boolean
    enable_cloud_save_error_popup_after_retry: boolean
    enable_command_handler_screen_manager: boolean
    enable_cow_info_csi: boolean
    enable_creator_details_shelf_m2: boolean
    enable_custom_survey_impression_logging: boolean
    enable_desktop_amsterdam_info_panels: boolean
    enable_desktop_companion_impression_on_first_visible: boolean
    enable_desktop_fountain_reaction_item_data_consumption: boolean
    enable_desktop_search_bigger_thumbs: boolean
    enable_desktop_search_bigger_thumbs_square: boolean
    enable_dma_post_enforcement: boolean
    enable_docked_chat_messages: boolean
    enable_dynamic_at_sign_for_channel_creation_handle: boolean
    enable_entity_store_from_dependency_injection: boolean
    enable_eom_webview_header: boolean
    enable_exit_confirmation_dialog: boolean
    enable_first_party_auth_v2_on_get_account_menu: boolean
    enable_flow_logging_p4e: boolean
    enable_fully_reactive_badge_shape: boolean
    enable_fully_reactive_chip_shape: boolean
    enable_fully_reactive_chip_view_model: boolean
    enable_gameplay: boolean
    enable_gel_log_commands: boolean
    enable_get_account_switcher_endpoint_on_webfe: boolean
    enable_ghost_view_rendering_limited_h5_client: boolean
    enable_google_payment_billing_command_client_support: boolean
    enable_handle_search_on_channel_switcher: boolean
    enable_handles_account_menu_switcher: boolean
    enable_handles_in_mention_suggest_posts: boolean
    enable_high_score: boolean
    enable_hlp_client_icon_pick: boolean
    enable_image_poll_post_creation: boolean
    enable_inline_preview_cancel_on_interaction: boolean
    enable_inline_shorts_on_wn: boolean
    enable_installment_wave2_view_agreement: boolean
    enable_interstitial_entity_check: boolean
    enable_ips_gating: boolean
    enable_is_extended_monitoring: boolean
    enable_isk_gating: boolean
    enable_lcr_emoji_fountain: boolean
    enable_lockup_view_model_with_dismissible: boolean
    enable_logging_first_user_action_after_game_ready: boolean
    enable_logging_only_game_clicks_as_first_user_action: boolean
    enable_lwe_web_mute: boolean
    enable_masthead_quartile_ping_fix: boolean
    enable_memberships_and_purchases: boolean
    enable_mentions_in_reposts: boolean
    enable_microformat_data: boolean
    enable_mini_app_iframe_loaded_logging: boolean
    enable_mini_app_microformats: boolean
    enable_mini_app_wiz_migration: boolean
    enable_mixed_direction_formatted_strings: boolean
    enable_multi_image_post_creation: boolean
    enable_names_handles_account_switcher: boolean
    enable_native_bridge_view_saved_playables: boolean
    enable_network_request_logging_on_game_events: boolean
    enable_new_channel_creation_for_id4all: boolean
    enable_on_yt_command_executor_command_to_navigate: boolean
    enable_pacf_slot_asde_infeed_h5: boolean
    enable_pacf_slot_asde_player_byte_h5: boolean
    enable_pacf_slot_asde_player_byte_h5_TV: boolean
    enable_payments_purchase_manager: boolean
    enable_pl_r_c_s: boolean
    enable_pl_r_si_fa: boolean
    enable_playable_a11y_label_with_badge_text: boolean
    enable_playable_container_save_button: boolean
    enable_playable_entity_save_menu_item: boolean
    enable_playable_title_tag_mweb: boolean
    enable_playables_deeplink: boolean
    enable_playables_destination: boolean
    enable_playables_fullscreen_refactor: boolean
    enable_playables_in_explore: boolean
    enable_playables_url_resolution: boolean
    enable_player_param_truncation_before_navigation_on_web: boolean
    enable_poll_choice_border_on_web: boolean
    enable_polymer_resin: boolean
    enable_polymer_resin_migration: boolean
    enable_populate_att_psd_in_abe_feedback: boolean
    enable_populate_psd_in_abe_feedback: boolean
    enable_post_cct_links: boolean
    enable_post_scheduling: boolean
    enable_premium_voluntary_pause: boolean
    enable_profile_cards_on_comments: boolean
    enable_programmed_playlist_color_sample: boolean
    enable_programmed_playlist_redesign: boolean
    enable_purchase_activity_in_paid_memberships: boolean
    enable_quiz_creation: boolean
    enable_reel_watch_sequence: boolean
    enable_reset_player_location: boolean
    enable_resolve_command_on_lwe_desktop: boolean
    enable_rfa_external_links: boolean
    enable_rfa_rate_limits: boolean
    enable_rta_manager: boolean
    enable_rta_nsm: boolean
    enable_save_high_score: boolean
    enable_scrolling_fix: boolean
    enable_sdf_in_player_video_h5: boolean
    enable_sdf_midroll_postroll_player_bytes_video_h5: boolean
    enable_sdf_preroll_player_bytes_video_h5: boolean
    enable_sdf_preroll_player_bytes_video_tv: boolean
    enable_sdk_performance_network_logging: boolean
    enable_sdk_performance_play_logging: boolean
    enable_sdk_performance_status_code_logging_launch: boolean
    enable_section_list_scroll_to_item_section_web: boolean
    enable_seedless_shorts_url: boolean
    enable_server_stitched_dai: boolean
    enable_service_ajax_csn: boolean
    enable_servlet_errors_streamz: boolean
    enable_servlet_streamz: boolean
    enable_sfv_audio_pivot_url: boolean
    enable_sfv_effect_pivot_url: boolean
    enable_shadydom_free_scoped_node_methods: boolean
    enable_shadydom_free_scoped_query_methods: boolean
    enable_shadydom_free_scoped_readonly_properties_batch_one: boolean
    enable_short_dr_for_desktop_launchable: boolean
    enable_skip_ad_guidance_prompt: boolean
    enable_skippable_ads_for_unplugged_ad_pod: boolean
    enable_smearing_expansion_dai: boolean
    enable_sparkles_web_clickable_description: boolean
    enable_structured_description_shorts_web_mweb: boolean
    enable_tectonic_ad_ux_for_halftime: boolean
    enable_third_party_info: boolean
    enable_time_out_messages: boolean
    enable_topsoil_wta_for_halftime_live_infra: boolean
    enable_unavailable_videos_watch_page: boolean
    enable_unified_cancellation_for_premium: boolean
    enable_variable_timeout_web: boolean
    enable_view_pronouns_on_main_app: boolean
    enable_watch_next_pause_autoplay_lact: boolean
    enable_web_96_bit_csn: boolean
    enable_web_gpay_command_spinner: boolean
    enable_web_ketchup_hero_animation: boolean
    enable_web_player_player_in_bar_feature: boolean
    enable_web_poster_hover_animation: boolean
    enable_web_shorts_audio_pivot: boolean
    enable_web_shorts_mention_pivot: boolean
    enable_web_shorts_preview_audio_pivot: boolean
    enable_web_shorts_save_audio_pivot: boolean
    enable_web_tiered_gel: boolean
    enable_window_constrained_buy_flow_dialog: boolean
    enable_wiz_next_lp2_msof: boolean
    enable_yoodle: boolean
    enable_your_playables_feed_entrypoint: boolean
    enable_ypc_spinners: boolean
    enable_yt_ata_iframe_authuser: boolean
    enable_ytc_refunds_submit_form_signal_action: boolean
    enable_ytc_self_serve_refunds: boolean
    endpoint_handler_logging_cleanup_killswitch: boolean
    err_on_pl_r_c: boolean
    export_networkless_options: boolean
    external_fullscreen: boolean
    external_fullscreen_with_edu: boolean
    faster_load_overlay: boolean
    fetch_bid_for_dclk_status: boolean
    fill_no_history_user_in_ip: boolean
    fill_no_history_user_in_watch_status: boolean
    fill_single_video_with_notify_to_lasr: boolean
    fill_view_models_on_web_vod: boolean
    fix_alignment_search_desktop_text_image_ads_small_screens: boolean
    fix_isd_logging: boolean
    gcf_config_store_enabled: boolean
    gda_enable_playlist_download: boolean
    global_spacebar_pause: boolean
    h5_companion_enable_adcpn_macro_substitution_for_click_pings: boolean
    h5_enable_generic_error_logging_event: boolean
    h5_inplayer_enable_adcpn_macro_substitution_for_click_pings: boolean
    h5_reset_cache_and_filter_before_update_masthead: boolean
    handles_in_mention_suggest_posts: boolean
    hide_endpoint_overflow_on_ytd_display_ad_renderer: boolean
    html5_enable_single_video_vod_ivar_on_pacf: boolean
    html5_force_debug_data_for_client_tmp_logs: boolean
    html5_log_trigger_events_with_debug_data: boolean
    html5_recognize_predict_start_cue_point: boolean
    html5_server_stitched_dai_group: boolean
    il_attach_cache_limit: boolean
    il_use_view_model_logging_context: boolean
    include_autoplay_count_in_playlists: boolean
    is_browser_support_for_webcam_streaming: boolean
    is_part_of_any_user_engagement_experiment: boolean
    json_condensed_response: boolean
    kev_adb_pg: boolean
    kevlar_app_shortcuts: boolean
    kevlar_appbehavior_attach_startup_tasks: boolean
    kevlar_appshell_service_worker: boolean
    kevlar_autofocus_menu_on_keyboard_nav: boolean
    kevlar_autonav_popup_filtering: boolean
    kevlar_av_eliminate_polling: boolean
    kevlar_c3po_to_wiz_3: boolean
    kevlar_c3po_to_wiz_4: boolean
    kevlar_cache_cold_load_response: boolean
    kevlar_cache_on_ttl_player: boolean
    kevlar_cache_on_ttl_search: boolean
    kevlar_calculate_grid_collapsible: boolean
    kevlar_cancel_scheduled_comment_jobs_on_navigate: boolean
    kevlar_channel_creation_form_resolver: boolean
    kevlar_channel_trailer_multi_attach: boolean
    kevlar_chapters_list_view_seek_by_chapter: boolean
    kevlar_clear_duplicate_pref_cookie: boolean
    kevlar_clear_non_displayable_url_params: boolean
    kevlar_client_enable_shorts_player_bootstrap: boolean
    kevlar_client_side_screens: boolean
    kevlar_command_handler: boolean
    kevlar_command_handler_clicks: boolean
    kevlar_command_handler_formatted_string: boolean
    kevlar_command_url: boolean
    kevlar_continue_playback_without_player_response: boolean
    kevlar_decorate_endpoint_with_onesie_config: boolean
    kevlar_delay_watch_initial_data: boolean
    kevlar_disable_background_prefetch: boolean
    kevlar_disable_pending_command: boolean
    kevlar_dragdrop_fast_scroll: boolean
    kevlar_dropdown_fix: boolean
    kevlar_droppable_prefetchable_requests: boolean
    kevlar_early_popup_close: boolean
    kevlar_enable_download_upsell_type_a: boolean
    kevlar_enable_editable_playlists: boolean
    kevlar_enable_em_offlineable_discovery: boolean
    kevlar_enable_reorderable_playlists: boolean
    kevlar_enable_shorts_prefetch_in_sequence: boolean
    kevlar_enable_shorts_response_chunking: boolean
    kevlar_enable_up_arrow: boolean
    kevlar_enable_wiz_icon_shape: boolean
    kevlar_exit_fullscreen_leaving_watch: boolean
    kevlar_fetch_pbj: boolean
    kevlar_fill_offline_availability_type_for_gda: boolean
    kevlar_fix_playlist_continuation: boolean
    kevlar_flexible_menu: boolean
    kevlar_fluid_touch_scroll: boolean
    kevlar_frontend_queue_recover: boolean
    kevlar_gel_error_routing: boolean
    kevlar_guide_refresh: boolean
    kevlar_help_use_locale: boolean
    kevlar_hide_playlist_playback_status: boolean
    kevlar_hide_pp_url_param: boolean
    kevlar_hide_time_continue_url_param: boolean
    kevlar_home_skeleton: boolean
    kevlar_js_fixes: boolean
    kevlar_keyboard_button_focus: boolean
    kevlar_larger_three_dot_tap: boolean
    kevlar_lazy_list_resume_for_autofill: boolean
    kevlar_local_innertube_response: boolean
    kevlar_log_updated_time_for_smart_downloads: boolean
    kevlar_macro_markers_keyboard_shortcut: boolean
    kevlar_mandatory_icon_data_killswitch: boolean
    kevlar_masthead_store: boolean
    kevlar_mealbar_above_player: boolean
    kevlar_miniplayer_expand_top: boolean
    kevlar_miniplayer_play_pause_on_scrim: boolean
    kevlar_miniplayer_queue_user_activation: boolean
    kevlar_mix_handle_first_endpoint_different: boolean
    kevlar_modern_sd: boolean
    kevlar_modern_sd_v2: boolean
    kevlar_next_cold_on_auth_change_detected: boolean
    kevlar_nitrate_driven_tooltips: boolean
    kevlar_no_autoscroll_on_playlist_hover: boolean
    kevlar_op_infra: boolean
    kevlar_op_warm_pages: boolean
    kevlar_pandown_polyfill: boolean
    kevlar_passive_event_listeners: boolean
    kevlar_playback_associated_queue: boolean
    kevlar_player_cached_load_config: boolean
    kevlar_player_check_ad_state_on_stop: boolean
    kevlar_player_load_player_no_op: boolean
    kevlar_player_new_bootstrap_adoption: boolean
    kevlar_player_playlist_use_local_index: boolean
    kevlar_player_watch_endpoint_navigation: boolean
    kevlar_playlist_drag_handles: boolean
    kevlar_playlist_use_x_close_button: boolean
    kevlar_poly_si_batch_j001: boolean
    kevlar_poly_si_batch_j002: boolean
    kevlar_poly_si_batch_j003: boolean
    kevlar_poly_si_batch_j004: boolean
    kevlar_poly_si_batch_j005: boolean
    kevlar_poly_si_batch_j006: boolean
    kevlar_poly_si_batch_j008: boolean
    kevlar_poly_si_batch_j009: boolean
    kevlar_poly_si_batch_j010: boolean
    kevlar_poly_si_batch_j011: boolean
    kevlar_poly_si_batch_j012: boolean
    kevlar_poly_si_batch_j013: boolean
    kevlar_poly_si_batch_j014: boolean
    kevlar_poly_si_batch_j015: boolean
    kevlar_poly_si_batch_j016: boolean
    kevlar_poly_si_batch_j017: boolean
    kevlar_poly_si_batch_j018: boolean
    kevlar_poly_si_batch_j019: boolean
    kevlar_poly_si_batch_j021: boolean
    kevlar_poly_si_batch_j022: boolean
    kevlar_poly_si_batch_j023: boolean
    kevlar_poly_si_batch_j024: boolean
    kevlar_poly_si_batch_j026: boolean
    kevlar_poly_si_batch_j032: boolean
    kevlar_poly_si_batch_j042: boolean
    kevlar_prefetch: boolean
    kevlar_prevent_polymer_dynamic_font_load: boolean
    kevlar_refresh_gesture: boolean
    kevlar_rendererstamper_event_listener: boolean
    kevlar_replace_short_to_short_history_state: boolean
    kevlar_request_sequencing: boolean
    kevlar_resolve_command_for_confirm_dialog: boolean
    kevlar_response_command_processor_page: boolean
    kevlar_scroll_chips_on_touch: boolean
    kevlar_scrollbar_rework: boolean
    kevlar_service_command_check: boolean
    kevlar_set_internal_player_size: boolean
    kevlar_shell_for_downloads_page: boolean
    kevlar_shorts_seedless_retry_initial_load: boolean
    kevlar_should_maintain_stable_list: boolean
    kevlar_show_em_dl_btn: boolean
    kevlar_show_em_dl_menu_item: boolean
    kevlar_show_em_dl_settings_tab: boolean
    kevlar_show_playlist_dl_btn: boolean
    kevlar_startup_lifecycle: boolean
    kevlar_structured_description_content_inline: boolean
    kevlar_system_icons: boolean
    kevlar_tabs_gesture: boolean
    kevlar_text_inline_expander_formatted_snippet: boolean
    kevlar_thumbnail_fluid: boolean
    kevlar_topbar_logo_fallback_home: boolean
    kevlar_touch_feedback: boolean
    kevlar_touch_gesture_ves: boolean
    kevlar_transcript_engagement_panel: boolean
    kevlar_tuner_run_default_comments_delay: boolean
    kevlar_tuner_should_defer_detach: boolean
    kevlar_typography_spacing_update: boolean
    kevlar_typography_update: boolean
    kevlar_unified_errors_init: boolean
    kevlar_use_response_ttl_to_invalidate_cache: boolean
    kevlar_use_vimio_behavior: boolean
    kevlar_use_wil_icons: boolean
    kevlar_use_ytd_player: boolean
    kevlar_variable_youtube_sans: boolean
    kevlar_vimio_use_shared_monitor: boolean
    kevlar_voice_logging_fix: boolean
    kevlar_voice_search_use_yt_endpoint: boolean
    kevlar_watch_cinematics: boolean
    kevlar_watch_color_update: boolean
    kevlar_watch_comments_ep_disable_theater: boolean
    kevlar_watch_drag_handles: boolean
    kevlar_watch_flexy_comments_manager: boolean
    kevlar_watch_flexy_miniplayer_manager: boolean
    kevlar_watch_flexy_playlist_manager: boolean
    kevlar_watch_flexy_theater_manager: boolean
    kevlar_watch_flexy_use_controller: boolean
    kevlar_watch_focus_on_engagement_panels: boolean
    kevlar_watch_gesture_pandown: boolean
    kevlar_watch_hide_comments_teaser: boolean
    kevlar_watch_hide_comments_while_panel_open: boolean
    kevlar_watch_js_panel_height: boolean
    kevlar_watch_metadata_refresh: boolean
    kevlar_watch_metadata_refresh_attached_subscribe: boolean
    kevlar_watch_metadata_refresh_clickable_description: boolean
    kevlar_watch_metadata_refresh_compact_view_count: boolean
    kevlar_watch_metadata_refresh_description_info_dedicated_line: boolean
    kevlar_watch_metadata_refresh_description_inline_expander: boolean
    kevlar_watch_metadata_refresh_description_primary_color: boolean
    kevlar_watch_metadata_refresh_for_live_killswitch: boolean
    kevlar_watch_metadata_refresh_full_width_description: boolean
    kevlar_watch_metadata_refresh_left_aligned_video_actions: boolean
    kevlar_watch_metadata_refresh_lower_case_video_actions: boolean
    kevlar_watch_metadata_refresh_narrower_item_wrap: boolean
    kevlar_watch_metadata_refresh_no_old_secondary_data: boolean
    kevlar_watch_metadata_refresh_relative_date: boolean
    kevlar_watch_metadata_refresh_top_aligned_actions: boolean
    kevlar_watch_modern_metapanel: boolean
    kevlar_watch_modern_panels: boolean
    kevlar_wiz_player_microformat: boolean
    kevlar_woffle: boolean
    kevlar_woffle_fallback_image: boolean
    kevlar_woffle_log_thumbnail_failure_ve: boolean
    kevlar_ytb_live_badges: boolean
    kids_enable_wiz_config: boolean
    killswitch_toggle_button_behavior_resolve_command: boolean
    live_chat_channel_activity: boolean
    live_chat_cow_visibility_set_up: boolean
    live_chat_emoji_picker_toggle_state: boolean
    live_chat_enable_controller_extraction: boolean
    live_chat_enable_rta_manager: boolean
    live_chat_enable_send_button_in_slow_mode: boolean
    live_chat_increased_min_height: boolean
    live_chat_mention_regex_update: boolean
    live_chat_over_playlist: boolean
    live_chat_require_space_for_autocomplete_emoji: boolean
    live_chat_web_banner_polls_update: boolean
    live_chat_web_use_emoji_manager_singleton: boolean
    live_chat_whole_message_clickable: boolean
    log_errors_through_nwl_on_retry: boolean
    log_gel_compression_latency: boolean
    log_heartbeat_with_lifecycles: boolean
    main_app_controller_extraction_batch_18: boolean
    main_app_controller_extraction_batch_19: boolean
    main_app_deprecate_child_decorator: boolean
    main_app_sink_wrapper_batch_1: boolean
    main_app_sink_wrapper_batch_10: boolean
    main_app_sink_wrapper_batch_11: boolean
    main_app_sink_wrapper_batch_12: boolean
    main_app_sink_wrapper_batch_13: boolean
    main_app_sink_wrapper_batch_14: boolean
    main_app_sink_wrapper_batch_15: boolean
    main_app_sink_wrapper_batch_2: boolean
    main_app_sink_wrapper_batch_3: boolean
    main_app_sink_wrapper_batch_4: boolean
    main_app_sink_wrapper_batch_5: boolean
    main_app_sink_wrapper_batch_6: boolean
    main_app_sink_wrapper_batch_7: boolean
    main_app_sink_wrapper_batch_8: boolean
    main_app_sink_wrapper_batch_9: boolean
    mdx_enable_privacy_disclosure_ui: boolean
    mdx_load_cast_api_bootstrap_script: boolean
    migrate_events_to_ts: boolean
    migrate_remaining_web_ad_badges_to_innertube: boolean
    modernize_structured_description_playlist_lockups_v2: boolean
    music_on_main_open_playlist_recommended_videos_in_miniplayer: boolean
    mweb_actions_command_handler: boolean
    mweb_attr_string_wiz: boolean
    mweb_channels_restyle_buttons_extra_padding: boolean
    mweb_channels_restyle_landscape_wider_buttons: boolean
    mweb_command_handler: boolean
    mweb_deprecate_skip_ve_logging: boolean
    mweb_disable_set_autonav_state_in_player: boolean
    mweb_enable_keto_batch_icons: boolean
    mweb_enable_search_big_thumbs: boolean
    mweb_killswitch_for_one_platform_channel_search_workaround: boolean
    mweb_logo_use_home_page_ve: boolean
    mweb_stop_truncating_meta_tags: boolean
    network_status_banner_display_none: boolean
    networkless_gel: boolean
    networkless_logging: boolean
    new_csn_storage_design: boolean
    nwl_send_fast_on_unload: boolean
    nwl_send_from_memory_when_online: boolean
    offline_error_handling: boolean
    pageid_as_header_web: boolean
    parent_tools_enable_wiz_config: boolean
    pause_ad_video_on_desktop_engagement_panel_click: boolean
    pdg_enable_flow_logging_for_super_chat: boolean
    pdg_enable_flow_logging_for_super_stickers: boolean
    playables_history_load_handling_killswitch: boolean
    player_bootstrap_method: boolean
    player_doubletap_to_seek: boolean
    player_enable_playback_playlist_change: boolean
    polymer_bad_build_labels: boolean
    polymer_verifiy_app_state: boolean
    polymer_ytdi_enable_global_injector: boolean
    problem_walkthrough_sd: boolean
    qoe_send_and_write: boolean
    read_data_from_web_component_wrapper: boolean
    record_app_crashed_web: boolean
    reels_enable_arrow_button_tooltip: boolean
    reels_enable_early_continuation: boolean
    reels_enable_new_latency_logging: boolean
    reels_enable_progress_bar_wiz: boolean
    reels_use_overlay_dark: boolean
    reels_web_use_contain_for_first_frame: boolean
    reels_web_use_pbs_first_shorts: boolean
    register_web_smartimations_component: boolean
    reload_without_polymer_innertube: boolean
    remove_masthead_channel_banner_on_refresh: boolean
    remove_yt_simple_endpoint_from_desktop_display_ad_title: boolean
    replace_client_url_parsing_with_server_signal: boolean
    replace_closure_window_with_updated_ytwindow_in_studio: boolean
    rfa_demotion_inline_ux_change: boolean
    rich_grid_resize_observer: boolean
    rich_grid_resize_observer_only: boolean
    rich_grid_watch_hide_rows_above: boolean
    scheduler_use_raf_by_default: boolean
    search_ui_enable_pve_buy_button: boolean
    search_ui_official_cards_enable_paid_virtual_event_buy_button: boolean
    searchbox_reporting: boolean
    serve_pdp_at_canonical_url: boolean
    service_worker_enabled: boolean
    service_worker_push_enabled: boolean
    service_worker_push_home_page_prompt: boolean
    service_worker_push_watch_page_prompt: boolean
    service_worker_static_routing_exclude_embed: boolean
    service_worker_static_routing_registration: boolean
    service_worker_subscribe_with_vapid_key: boolean
    shared_enable_controller_extraction: boolean
    shared_enable_sink_wrapping: boolean
    shell_load_gcf: boolean
    shorts_controller_retrieve_seedless_sequence: boolean
    shorts_desktop_watch_while_p2: boolean
    shorts_desktop_watch_while_sdp: boolean
    shorts_in_playlists_web: boolean
    shorts_overlay_reshuffle: boolean
    should_clear_video_data_on_player_cued_unstarted: boolean
    show_eom_dialog_at_attach: boolean
    skip_invalid_ytcsi_ticks: boolean
    skip_ls_gel_retry: boolean
    skip_setting_info_in_csi_data_object: boolean
    smarter_ve_dedupping: boolean
    smartimation_background: boolean
    sponsorships_free_creator_gifting: boolean
    start_client_gcf: boolean
    start_sending_config_hash: boolean
    suppress_error_204_logging: boolean
    swatcheroo_ep_use_inline_expander: boolean
    transport_use_scheduler: boolean
    trigger_impression_pings_on_view_search_desktop: boolean
    unplugged_enable_wiz_config: boolean
    update_chrome_api_monitoring_allowed_features: boolean
    update_log_event_config: boolean
    update_ytWindow_library_use_closure_window_library: boolean
    use_ads_engagement_panel_desktop_footer_cta: boolean
    use_better_post_dismissals: boolean
    use_border_and_grid_wrapping_on_desktop_panel_tiles: boolean
    use_color_palettes_modern_collections_v2: boolean
    use_core_sm: boolean
    use_csi_stp_handler: boolean
    use_event_time_ms_header: boolean
    use_fifo_for_networkless: boolean
    use_flow_bottom_bar_view_model_in_flow_step_renderer: boolean
    use_infogel_early_logging: boolean
    use_new_in_memory_storage: boolean
    use_not_now_dl_upsell_dismiss_cta: boolean
    use_player_abuse_bg_library: boolean
    use_request_time_ms_header: boolean
    use_rta_manager_for_async: boolean
    use_session_based_sampling: boolean
    use_ts_visibilitylogger: boolean
    use_unified_flag_accessor: boolean
    use_watch_fragments2: boolean
    use_ytd_player_for_desktop_masthead: boolean
    vss_final_ping_send_and_write: boolean
    vss_playback_use_send_and_write: boolean
    warm_load_nav_start_web: boolean
    warm_op_csn_cleanup: boolean
    web_always_load_chat_support: boolean
    web_always_show_threedot_menu: boolean
    web_amsterdam_post_mvp_playlists: boolean
    web_animated_actions: boolean
    web_animated_actions_v2: boolean
    web_animated_like: boolean
    web_animated_like_lazy_load: boolean
    web_api_url: boolean
    web_appshell_purge_trigger: boolean
    web_appshell_refresh_trigger: boolean
    web_autonav_allow_off_by_default: boolean
    web_avatar_shape_inline_icon: boolean
    web_bookmark_playlist_save_icon: boolean
    web_button_rework: boolean
    web_button_rework_with_live: boolean
    web_chat_prevent_chat_header_overflow: boolean
    web_cinematic_light_theme: boolean
    web_collect_offline_state: boolean
    web_consolidated_panel: boolean
    web_csi_action_sampling_enabled: boolean
    web_csi_debug_sample_enabled: boolean
    web_darker_dark_theme: boolean
    web_darker_dark_theme_deprecate: boolean
    web_darker_dark_theme_live_chat: boolean
    web_dedupe_ve_grafting: boolean
    web_defer_shorts_ui: boolean
    web_defer_shorts_ui_phase2: boolean
    web_disable_channels_chapter_entrypoint: boolean
    web_disable_vertical_scroll_chips: boolean
    web_early_logging_time_init: boolean
    web_enable_ab_em_rsp: boolean
    web_enable_ab_rsp_cl: boolean
    web_enable_abd_ref: boolean
    web_enable_adaptive_appl_signal: boolean
    web_enable_deeper_metadata_highlight_styling: boolean
    web_enable_dynamic_metadata: boolean
    web_enable_dynamic_suggested_action: boolean
    web_enable_error_204: boolean
    web_enable_feedback_endpoint_resolver: boolean
    web_enable_feedback_endpoint_resolver_batch_2: boolean
    web_enable_history_cache_map: boolean
    web_enable_history_sandbox: boolean
    web_enable_horizontal_video_attributes_section: boolean
    web_enable_miniplayer_refactor: boolean
    web_enable_rich_grid_node_reordering: boolean
    web_enable_youtab: boolean
    web_engagement_panel_show_description: boolean
    web_ep_restyling: boolean
    web_fill_shorts_detailed_accessibility: boolean
    web_filled_subscribed_button: boolean
    web_fix_back_button_player_loading: boolean
    web_fix_dynamic_metadata_diacritic: boolean
    web_fix_fine_scrubbing_false_play: boolean
    web_fix_missing_action_buttons: boolean
    web_fix_segmented_like_dislike_undefined: boolean
    web_forward_command_on_pbj: boolean
    web_gel_timeout_cap: boolean
    web_guide_ui_refresh: boolean
    web_header_eu_about_these_results: boolean
    web_hide_autonav_keyline: boolean
    web_home_inline_shorts_groups: boolean
    web_horizontal_list_focus_bugfix: boolean
    web_imp_enable_thumbnail_position_check: boolean
    web_infocards_teaser_show_logging_fix: boolean
    web_inline_player_enabled: boolean
    web_kevlar_enable_adaptive_signals: boolean
    web_localized_cc_icon: boolean
    web_log_feedback_on_submitted: boolean
    web_log_memory_total_kbytes: boolean
    web_log_player_watch_next_ticks: boolean
    web_log_reels_ticks: boolean
    web_masthead_visited_channel_color_fix: boolean
    web_memoize_inflight_requests: boolean
    web_modern_ads: boolean
    web_modern_buttons: boolean
    web_modern_buttons_bl_survey: boolean
    web_modern_chips: boolean
    web_modern_collections: boolean
    web_modern_collections_v2: boolean
    web_modern_dialogs: boolean
    web_modern_player_settings_quality_bottom: boolean
    web_modern_playlists: boolean
    web_modern_tabs: boolean
    web_modern_typography: boolean
    web_move_autoplay_video_under_chip: boolean
    web_now_playing_badge: boolean
    web_one_platform_error_handling: boolean
    web_persist_server_autonav_state_on_client: boolean
    web_player_add_ve_conversion_logging_to_outbound_links: boolean
    web_player_autonav_empty_suggestions_fix: boolean
    web_player_autonav_next_button_renderer: boolean
    web_player_autonav_toggle_always_listen: boolean
    web_player_autonav_use_server_provided_state: boolean
    web_player_disable_inline_scrubbing: boolean
    web_player_enable_cultural_moment_overlay: boolean
    web_player_enable_early_warning_snackbar: boolean
    web_player_enable_featured_product_banner_exclusives_on_desktop: boolean
    web_player_enable_featured_product_banner_price_deals_on_desktop: boolean
    web_player_enable_featured_product_banner_promotion_text_on_desktop: boolean
    web_player_enable_info_button_in_banner_on_desktop: boolean
    web_player_enable_open_menu_item_from_command: boolean
    web_player_enable_overflow_button_in_banner_on_desktop: boolean
    web_player_enable_premium_hbr_in_h5_api: boolean
    web_player_enable_premium_hbr_playback_cap: boolean
    web_player_enable_vod_featured_product_banner_on_desktop: boolean
    web_player_entities_middleware: boolean
    web_player_log_click_before_generating_ve_conversion_params: boolean
    web_player_move_autonav_toggle: boolean
    web_player_should_honor_include_asr_setting: boolean
    web_player_small_hbp_settings_menu: boolean
    web_player_split_event_bus: boolean
    web_player_topify_subtitles_for_shorts: boolean
    web_player_use_heartbeat_poll_delay_ms: boolean
    web_player_use_new_api_for_quality_pullback: boolean
    web_player_ve_conversion_fixes_for_channel_info: boolean
    web_prefer_local_wn_response: boolean
    web_prefetch_preload_video: boolean
    web_prs_testing_mode_killswitch: boolean
    web_reels_reduce_shorts_margin: boolean
    web_rendererstamper_event_listener: boolean
    web_replace_thumbnail_with_image: boolean
    web_resizable_advertiser_banner_on_masthead: boolean
    web_resizable_advertiser_banner_on_masthead_safari_fix: boolean
    web_rich_grid_media_use_decorated_avatar_view_model: boolean
    web_rich_shelf_show_less_button: boolean
    web_rich_shelf_show_less_button_overlapping_divider: boolean
    web_rich_shelf_show_more_button: boolean
    web_rich_shelf_show_more_button_overlapping_divider: boolean
    web_rounded_thumbnails: boolean
    web_scheduler_auto_init: boolean
    web_segmented_like_dislike_button: boolean
    web_sheets_ui_refresh: boolean
    web_shorts_badge_migration: boolean
    web_shorts_comment_stickers: boolean
    web_shorts_deflate_inactive_slides_aggressive: boolean
    web_shorts_scrubber_bar: boolean
    web_shorts_shelf_on_search: boolean
    web_shorts_skip_loading_same_index: boolean
    web_shorts_small_screen_watch_while: boolean
    web_shorts_sound_metadata: boolean
    web_shorts_suggested_action_no_bvm: boolean
    web_shorts_surveys: boolean
    web_simple_scriptloader: boolean
    web_simple_styleloader: boolean
    web_snackbar_ui_refresh: boolean
    web_speedmaster_spacebar_control: boolean
    web_structured_description_show_more: boolean
    web_suggested_actions_backwards_compatible: boolean
    web_suggestion_box_bolder: boolean
    web_suggestion_box_restyle: boolean
    web_supports_animations_api: boolean
    web_thumbnail_overlay_badge_shape: boolean
    web_timed_sync_manager: boolean
    web_timeline_view: boolean
    web_trailer_imp_for_premieres: boolean
    web_update_flexible_buttons_after_renderidom: boolean
    web_use_cache_for_image_fallback: boolean
    web_vision_pro_detection_killswitch: boolean
    web_watch_chips_mask_fade: boolean
    web_watch_cinematics_preferred_reduced_motion_default_disabled: boolean
    web_watch_fill_description_more_text: boolean
    web_watch_get_updated_metadata_manager: boolean
    web_watch_get_updated_metadata_response_processing: boolean
    web_watch_rounded_player_large: boolean
    web_watch_theater_chat: boolean
    web_watch_theater_fixed_chat: boolean
    web_watch_typography_title_headline_xs: boolean
    web_watch_updated_metadata_server_initial_delay: boolean
    web_yt_config_context: boolean
    webfe_disable_ab_em_plb: boolean
    wil_icon_render_when_idle: boolean
    wiz_diff_overwritable: boolean
    wiz_memoize_stamper_items: boolean
    wiz_prevent_watched_double_logging: boolean
    wiz_use_generic_logging_infra: boolean
    woffle_clean_up_after_entity_migration: boolean
    woffle_enable_download_status: boolean
    woffle_orchestration: boolean
    woffle_playlist_only_show_completed: boolean
    woffle_playlist_optimization: boolean
    woffle_playlist_visitor_fix: boolean
    woffle_used_state_report: boolean
    ww_squeezeback_killswitch: boolean
    yt_network_manager_component_to_lib_killswitch: boolean
    ytidb_clear_embedded_player: boolean
    ytidb_fetch_datasync_ids_for_data_cleanup: boolean
    H5_async_logging_delay_ms: number
    app_shell_asset_log_fraction: number
    autoplay_pause_by_lact_sampling_fraction: number
    browse_ajax_log_warning_fraction: number
    cinematic_watch_effect_opacity: number
    dynamic_metadata_update_interaction_delay_period_sec: number
    formatted_description_log_warning_fraction: number
    kevlar_tuner_clamp_device_pixel_ratio: number
    kevlar_tuner_thumbnail_factor: number
    kevlar_unified_player_logging_threshold: number
    log_window_onerror_fraction: number
    miniplayer_refactor_threshold_flag: number
    miniplayer_visibility_threshold_flag: number
    polymer_property_access_logging_percent: number
    polymer_report_client_url_requested_rate: number
    polymer_report_missing_web_navigation_endpoint_rate: number
    prefetch_coordinator_error_logging_sampling_rate: number
    tv_pacf_logging_sample_rate: number
    web_shorts_error_logging_threshold: number
    web_shorts_intersection_observer_threshold_override: number
    web_system_health_fraction: number
    ytidb_transaction_ended_event_rate_limit: number
    ytidb_transaction_ended_event_rate_limit_session: number
    ytidb_transaction_ended_event_rate_limit_transaction: number
    active_time_update_interval_ms: number
    autoplay_pause_by_lact_sec: number
    autoplay_time: number
    autoplay_time_for_fullscreen: number
    autoplay_time_for_music_content: number
    botguard_async_snapshot_timeout_ms: number
    check_navigator_accuracy_timeout_ms: number
    cinematic_watch_css_filter_blur_strength: number
    cinematic_watch_fade_out_duration: number
    cinematic_watch_transition_frame_rate: number
    client_streamz_web_flush_count: number
    client_streamz_web_flush_interval_seconds: number
    close_webview_delay_ms: number
    cloud_save_game_data_rate_limit_ms: number
    compression_disable_point: number
    desktop_fountain_emoji_size_px: number
    desktop_search_suggestion_tap_target: number
    external_fullscreen_button_click_threshold: number
    external_fullscreen_button_shown_threshold: number
    gel_min_batch_size: number
    gel_queue_timeout_max_ms: number
    get_async_timeout_ms: number
    hide_cta_for_home_web_video_ads_animate_in_time: number
    high_priority_flyout_frequency: number
    initial_gel_batch_timeout: number
    innertube_request_limit_ms: number
    kevlar_lockup_hover_delay: number
    kevlar_mini_guide_width_threshold: number
    kevlar_persistent_guide_width_threshold: number
    kevlar_time_caching_end_threshold: number
    kevlar_time_caching_start_threshold: number
    kevlar_tooltip_impression_cap: number
    kevlar_tuner_default_comments_delay: number
    kevlar_tuner_scheduler_soft_state_timer_ms: number
    kevlar_tuner_visibility_time_between_jobs_ms: number
    kevlar_watch_flexy_metadata_height: number
    kevlar_watch_grid_below_player_value: number
    kevlar_watch_grid_sidebar_min_width: number
    kevlar_watch_max_player_width: number
    kevlar_watch_metadata_refresh_description_lines: number
    kevlar_watch_page_columns_top_padding: number
    kevlar_watch_page_horizontal_margin: number
    kevlar_watch_page_margin: number
    kevlar_watch_player_min_height: number
    kevlar_watch_secondary_width: number
    kevlar_watch_two_column_width_threshold: number
    live_chat_chunk_rendering: number
    live_chat_chunking_qps_threshold: number
    live_chat_emoji_picker_restyle_bottom_px: number
    live_chat_emoji_picker_restyle_height_percent: number
    live_chat_emoji_picker_restyle_height_px: number
    live_chat_emoji_picker_restyle_width_px: number
    live_chat_max_chunk_size: number
    live_chat_min_chunk_interval_ms: number
    live_chat_web_tooltip_timeout_ms: number
    live_reactions_desktop_fab_relocation_mode: number
    max_body_size_to_compress: number
    max_prefetch_window_sec_for_livestream_optimization: number
    min_prefetch_offset_sec_for_livestream_optimization: number
    mweb_history_manager_cache_size: number
    mweb_history_manager_w2w_ttl: number
    network_polling_interval: number
    pbj_navigate_limit: number
    play_click_interval_ms: number
    play_ping_interval_ms: number
    post_type_icons_rearrange: number
    prefetch_comments_ms_after_video: number
    prefetch_coordinator_command_timeout_ms: number
    prefetch_coordinator_max_inflight_requests: number
    rich_grid_dynamic_offset_anchor_width: number
    rich_grid_dynamic_offset_lower_bound: number
    rich_grid_dynamic_offset_offset_per_100: number
    rich_grid_max_item_width: number
    rich_grid_min_item_width: number
    send_config_hash_timer: number
    service_worker_push_logged_out_prompt_watches: number
    service_worker_push_prompt_cap: number
    service_worker_push_prompt_delay_microseconds: number
    slow_compressions_before_abandon_count: number
    swatcheroo_pbs_max_delay_ms: number
    swatcheroo_provide_all_data_delay_ms: number
    swatcheroo_rich_grid_delay: number
    teaser_carousel_desc_lines: number
    user_engagement_experiments_rate_limit_ms: number
    user_mention_suggestions_edu_impression_cap: number
    visibility_time_between_jobs_ms: number
    web_cold_open_animation_initial_delay: number
    web_emulated_idle_callback_delay: number
    web_foreground_heartbeat_interval_ms: number
    web_gel_debounce_ms: number
    web_gnome_max_shelf_depth: number
    web_home_min_first_row_for_groups: number
    web_home_minimum_rows_of_videos_at_start: number
    web_home_minimum_rows_of_videos_at_start_client: number
    web_home_minimum_rows_of_videos_between_sections: number
    web_logging_max_batch: number
    web_reduce_shorts_margin: number
    web_reels_enable_audio_pivot_in_panel: number
    web_search_inline_player_triggering_delay: number
    web_shorts_deflate_inactive_slides_aggressive_distance: number
    web_shorts_inline_playback_preview_ms: number
    web_smoothness_test_duration_ms: number
    web_smoothness_test_method: number
    wil_icon_max_concurrent_fetches: number
    wn_grid_max_item_width: number
    wn_grid_min_item_width: number
    yoodle_end_time_utc: number
    yoodle_start_time_utc: number
    ytidb_remake_db_retries: number
    ytidb_reopen_db_retries: number
    WebClientReleaseProcessCritical__youtube_web_client_version_override: string
    asset_caching_http_max_age: string
    comment_input_box_triggering_strategy: string
    debug_forced_internalcountrycode: string
    desktop_search_bigger_thumbs_style: string
    desktop_searchbar_style: string
    embeds_web_synth_ch_headers_banned_urls_regex: string
    il_payload_scraping: string
    kevlar_duplicate_pref_cookie_domain_override: string
    kevlar_link_capturing_mode: string
    live_chat_unicode_emoji_json_url: string
    loading_bar_progress_calculation: string
    place_pivot_triggering_container_alternate: string
    place_pivot_triggering_counterfactual_container_alternate: string
    podcast_show_lockup_style_web: string
    polymer_task_manager_status: string
    reels_action_justified_content: string
    reels_metadata_justified_content: string
    reels_navigation_justify_content: string
    search_overview_link_style: string
    service_worker_push_force_notification_prompt_tag: string
    service_worker_scope: string
    talk_to_recs_question_response_ui: string
    web_client_version_override: string
    web_home_feed_reload_experience: string
    web_modern_subscribe_style: string
    web_shorts_expanded_overlay_type: string
    web_shorts_overlay_vertical_orientation: string
    yoodle_base_url: string
    conditional_lab_ids: number[]
    guide_business_info_countries: string[]
    guide_legal_footer_enabled_countries: string[]
    html5_profiler_trace_enums: any[]
    kevlar_command_handler_command_banlist: any[]
    kevlar_page_service_url_prefix_carveouts: any[]
    live_chat_dynamic_chunking_interval_range: any[]
    live_chat_dynamic_chunking_traffic_range: any[]
    mini_app_ids_without_game_ready: string[]
    web_op_signal_type_banlist: any[]
}

export interface GoogleFeedbackProductData {
    polymer: string
    polymer2: string
    accept_language: string
}

export interface InnertubeContext {
    client: Client
    user: User
    request: Request
    clickTracking: ClickTracking
}

export interface Client {
    hl: string
    gl: string
    remoteHost: string
    deviceMake: string
    deviceModel: string
    visitorData: string
    userAgent: string
    clientName: string
    clientVersion: string
    osName: string
    osVersion: string
    originalUrl: string
    platform: string
    clientFormFactor: string
    configInfo: ConfigInfo
    userInterfaceTheme: string
    timeZone: string
    browserName: string
    browserVersion: string
    locationPlayabilityToken: string
    acceptHeader: string
    deviceExperimentId: string
}

export interface ConfigInfo {
    appInstallData: string
}

export interface User {
    lockedSafetyMode: boolean
}

export interface Request {
    useSsl: boolean
    consistencyTokenJars: ConsistencyTokenJar[]
}

export interface ConsistencyTokenJar {
    encryptedTokenJarContents: string
}

export interface ClickTracking {
    clickTrackingParams: string
}

export interface LatestEcatcherServiceTrackingParams {
    "client.name": string
}

export interface Scheduler {
    useRaf: boolean
    timeout: number
}

export interface WebPlayerContextConfigs {
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_WATCH: WebPlayerContextConfigIdKevlarWatch
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_CHANNEL_TRAILER: WebPlayerContextConfigIdKevlarChannelTrailer
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_PLAYLIST_OVERVIEW: WebPlayerContextConfigIdKevlarPlaylistOverview
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_VERTICAL_LANDING_PAGE_PROMO: WebPlayerContextConfigIdKevlarVerticalLandingPagePromo
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_SHORTS: WebPlayerContextConfigIdKevlarShorts
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_SPONSORSHIPS_OFFER: WebPlayerContextConfigIdKevlarSponsorshipsOffer
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_INLINE_PREVIEW: WebPlayerContextConfigIdKevlarInlinePreview
    WEB_PLAYER_CONTEXT_CONFIG_ID_HANDLES_CLAIMING: WebPlayerContextConfigIdHandlesClaiming
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_SFV_AUDIO_ITEM: WebPlayerContextConfigIdKevlarSfvAudioItem
    WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_MASTHEAD_AD: WebPlayerContextConfigIdKevlarMastheadAd
}

export interface WebPlayerContextConfigIdKevlarWatch {
    transparentBackground: boolean
    showMiniplayerButton: boolean
    externalFullscreen: boolean
    showMiniplayerUiWhenMinimized: boolean
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    device: Device
    serializedExperimentIds: string
    serializedExperimentFlags: string
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    csiPageType: string
    authorizedUserIndex: number
    datasyncId: string
    allowWoffleManagement: boolean
    cinematicSettingsAvailable: boolean
    canaryStage: string
}

export interface Device {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarChannelTrailer {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    device: Device2
    serializedExperimentIds: string
    serializedExperimentFlags: string
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    csiPageType: string
    authorizedUserIndex: number
    datasyncId: string
    canaryStage: string
}

export interface Device2 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarPlaylistOverview {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    device: Device3
    serializedExperimentIds: string
    serializedExperimentFlags: string
    disableSharing: boolean
    hideInfo: boolean
    disableWatchLater: boolean
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    csiPageType: string
    authorizedUserIndex: number
    datasyncId: string
    canaryStage: string
}

export interface Device3 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarVerticalLandingPagePromo {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    controlsType: number
    disableRelatedVideos: boolean
    annotationsLoadPolicy: number
    device: Device4
    serializedExperimentIds: string
    serializedExperimentFlags: string
    hideInfo: boolean
    startMuted: boolean
    enableMutedAutoplay: boolean
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    csiPageType: string
    authorizedUserIndex: number
    datasyncId: string
    canaryStage: string
}

export interface Device4 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarShorts {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    controlsType: number
    disableKeyboardControls: boolean
    disableRelatedVideos: boolean
    annotationsLoadPolicy: number
    device: Device5
    serializedExperimentIds: string
    serializedExperimentFlags: string
    hideInfo: boolean
    disableFullscreen: boolean
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    authorizedUserIndex: number
    datasyncId: string
    storeUserVolume: boolean
    disableSeek: boolean
    disablePaidContentOverlay: boolean
    preferGapless: boolean
    canaryStage: string
}

export interface Device5 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarSponsorshipsOffer {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    disableRelatedVideos: boolean
    annotationsLoadPolicy: number
    device: Device6
    serializedExperimentIds: string
    serializedExperimentFlags: string
    disableFullscreen: boolean
    cspNonce: string
    canaryState: string
    authorizedUserIndex: number
    datasyncId: string
    canaryStage: string
}

export interface Device6 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarInlinePreview {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    controlsType: number
    disableKeyboardControls: boolean
    device: Device7
    serializedExperimentIds: string
    serializedExperimentFlags: string
    disableFullscreen: boolean
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    csiPageType: string
    authorizedUserIndex: number
    disableMdxCast: boolean
    datasyncId: string
    disablePaidContentOverlay: boolean
    canaryStage: string
}

export interface Device7 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdHandlesClaiming {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    disableRelatedVideos: boolean
    device: Device8
    serializedExperimentIds: string
    serializedExperimentFlags: string
    cspNonce: string
    canaryState: string
    authorizedUserIndex: number
    datasyncId: string
    canaryStage: string
}

export interface Device8 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarSfvAudioItem {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    eventLabel: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    device: Device9
    serializedExperimentIds: string
    serializedExperimentFlags: string
    cspNonce: string
    canaryState: string
    enableCsiLogging: boolean
    authorizedUserIndex: number
    deviceIsAudioOnly: boolean
    datasyncId: string
    canaryStage: string
}

export interface Device9 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface WebPlayerContextConfigIdKevlarMastheadAd {
    rootElementId: string
    jsUrl: string
    cssUrl: string
    contextId: string
    contentRegion: string
    hl: string
    hostLanguage: string
    playerStyle: string
    innertubeApiKey: string
    innertubeApiVersion: string
    innertubeContextClientVersion: string
    controlsType: number
    disableKeyboardControls: boolean
    disableRelatedVideos: boolean
    annotationsLoadPolicy: number
    device: Device10
    serializedExperimentIds: string
    serializedExperimentFlags: string
    disableSharing: boolean
    disableWatchLater: boolean
    startMuted: boolean
    enableMutedAutoplay: boolean
    disableFullscreen: boolean
    cspNonce: string
    canaryState: string
    authorizedUserIndex: number
    datasyncId: string
    disableSeek: boolean
    canaryStage: string
    disableStaleness: boolean
}

export interface Device10 {
    brand: string
    model: string
    browser: string
    browserVersion: string
    os: string
    osVersion: string
    platform: string
    interfaceName: string
    interfaceVersion: string
}

export interface LiveChatBaseTangoConfig {
    apiKey: string
    channelUri: string
    clientName: string
    requiresAuthToken: boolean
    senderUri: string
    useNewTango: boolean
}

export interface WorkerPerformanceUrl {
    privateDoNotAccessOrElseTrustedResourceUrlWrappedValue: string
}

export interface RawColdConfigGroup {
    configData: string
    mainAppColdConfig: MainAppColdConfig
}

export interface MainAppColdConfig {
    iosSsoSafariFsiPromoEnabled: boolean
    iosTodayWidgetEnabled: boolean
    iosEnableDynamicFontSizing: boolean
    enableMobileAutoOffline: boolean
    androidEnablePip: boolean
    postsV2: boolean
    enableDetailedNetworkStatusReporting: boolean
    hourToReportNetworkStatus: number
    networkStatusReportingWindowSecs: number
    iosSearchviewRefactoryEnabled: boolean
    ngwFlexyEnabled: boolean
    iosWatchExpandTransitionWithoutSnapshot: boolean
    androidNgwUiEnabled: boolean
    androidThumbnailMonitorEnabled: boolean
    androidThumbnailMonitorCount: number
    androidThumbnailMonitorMinimumWidth: number
    enableGhostCards: boolean
    enableInlineMuted: boolean
    ngwFlexyMaxCropRatio: number
    androidRestoreBrowseContentsFromBackStack: boolean
    searchHintExp: string
}

export interface RawHotConfigGroup {
    mainAppHotConfig: MainAppHotConfig
    loggingHotConfig: LoggingHotConfig
}

export interface MainAppHotConfig {
    iosWatchExpandTransition: boolean
    iosEarlySetWatchTransition: boolean
    exposeConfigRefreshSetting: boolean
    iosEnableSearchButtonOnPlayerOverlay: boolean
    iosMinimumTooltipDurationMsecs: number
    iosFreshHomeIntervalSecs: number
    iosFreshSubscriptionsIntervalSecs: number
    iosTodayWidgetRefreshIntervalSecs: number
    iosFreshNotificationsInboxIntervalSecs: number
    signedOutNotificationsIosPrompt: boolean
    iosFreshFullRefresh: boolean
}

export interface LoggingHotConfig {
    eventLoggingConfig: EventLoggingConfig
    csiConfig: CsiConfig
}

export interface EventLoggingConfig {
    enabled: boolean
    payloadPolicies: PayloadPolicy[]
    maxAgeHours: number
    requestRetryEnabled: boolean
    retryConfig: RetryConfig
    shouldForceSetAllPayloadsToImmediateTier: boolean
}

export interface PayloadPolicy {
    enabled: boolean
    payloadNumber: number
    tier: string
}

export interface RetryConfig {
    fixedBatchRetryEnabled: boolean
}

export interface CsiConfig {
    loggingUrl: LoggingUrl
    iosHomeActionThroughCsi204Enabled: boolean
    browseActionThroughCsi204Enabled: boolean
    browseActionThroughGelEnabled: boolean
    debugSampleWeight: number
    debugTicks: DebugTick[]
}

export interface LoggingUrl {
    baseUrl: string
}

export interface DebugTick {
    tickName: string
}

export interface PersistIdentityIframeUrl {
    privateDoNotAccessOrElseTrustedResourceUrlWrappedValue: string
}

export interface WorkerSerializationUrl {
    privateDoNotAccessOrElseTrustedResourceUrlWrappedValue: string
}

export interface SboxLabels {
    SUGGESTION_DISMISS_LABEL: string
    SUGGESTION_DISMISSED_LABEL: string
}

export interface SboxSettings {
    HAS_ON_SCREEN_KEYBOARD: boolean
    IS_FUSION: boolean
    IS_POLYMER: boolean
    PSUGGEST_TOKEN: string
    REQUEST_DOMAIN: string
    REQUEST_LANGUAGE: string
    SEND_VISITOR_DATA: boolean
    SEARCHBOX_BEHAVIOR_EXPERIMENT: string
    SEARCHBOX_ENABLE_REFINEMENT_SUGGEST: boolean
    SEARCHBOX_TAP_TARGET_EXPERIMENT: number
    SEARCHBOX_ZERO_TYPING_SUGGEST_USE_REGULAR_SUGGEST: string
    SUGG_EXP_ID: string
    SEARCHBOX_HOST_OVERRIDE: string
    HIDE_REMOVE_LINK: boolean
}
